from tkinter import *
from PIL import ImageTk, Image
import os

root = Tk()
root.title('Semne')
root.geometry('{}x{}'.format(1250, 660))
img = ImageTk.PhotoImage(Image.open("/Users/teodorabotez/Desktop/Licenta/Cod/poze-semne/37-telefon.png"))
panel = Label(root, image = img)
panel.place(x=30, y=70, anchor="center")
img2 = ImageTk.PhotoImage(Image.open("/Users/teodorabotez/Desktop/Licenta/Cod/poze-semne/38-casa.png"))
panel2 = Label(root, image = img2)
panel2.place(x=160, y=70, anchor="center")
img3 = ImageTk.PhotoImage(Image.open("/Users/teodorabotez/Desktop/Licenta/Cod/poze-semne/semne.png"))
panel3 = Label(root, image = img3)
panel3.place(x=900, y=300, anchor="center")
img4 = ImageTk.PhotoImage(Image.open("/Users/teodorabotez/Desktop/Licenta/Cod/poze-semne/39-dragoste2.png"))
panel4 = Label(root, image = img4)
panel4.place(x=260, y=70, anchor="center")
img5 = ImageTk.PhotoImage(Image.open("/Users/teodorabotez/Desktop/Licenta/Cod/poze-semne/40-prieten.png"))
panel5 = Label(root, image = img5)
panel5.place(x=360, y=70, anchor="center")
img6 = ImageTk.PhotoImage(Image.open("/Users/teodorabotez/Desktop/Licenta/Cod/poze-semne/41-mai mult.png"))
panel6 = Label(root, image = img6)
panel6.place(x=460, y=70, anchor="center")
img7 = ImageTk.PhotoImage(Image.open("/Users/teodorabotez/Desktop/Licenta/Cod/poze-semne/pronume.png"))
panel7 = Label(root, image = img7)
panel7.place(x=250, y=400, anchor="center")
root.mainloop()